[package]
name = "lazy-st"
version = "0.2.1"
authors = [
  "Jonathan Reem <jonathan.reem@gmail.com>",
  "Michael Färber <michael.faerber@gedenkt.at>"
]
edition = "2018"

description = "Single-threaded lazy evaluation"
license = "MIT"

[dependencies]
